class CategoryMappings:
    def __init__(self):
        self.categories = [
            "food", "music", "hobbies", "video games", "streaming", 
            "vtubing", "live2d rigging", "drawing", "coding", "projects", 
            "social media and content creation"
        ]
        self.base_category_mapping = {
            "music": [
                    "instrument", "music", "song",
                    "band", "artist", "genre", "album",
                    "track", "playlist", "melody", "listen",
                    "play", "sing", "compose", "lyric",
                    "spotify", "streaming", "concert", "radio",
                    "festival", "headphones", "earbuds", "speakers"
                ],
            "food": [
                "food", "dish", "meal", "snack", "drink", "beverage",
                "breakfast", "lunch", "dinner", "brunch",
                "menu", "restaurant", "dining", "cuisine",
                "taste", "flavor", "eat", "cook", "bake", "prepare",
                "recipe", "ingredient", "spice", "herb",
                "appetizer", "main course", "dessert",
                "grill", "roast", "fry", "boil", "steam",
                "kitchen", "oven", "stove", "cookware",
                "chef", "culinary", "gastronomy",
                "vegetarian", "vegan", "gluten-free", "organic",
                "homemade", "takeout", "fast food",
                "nutritious", "delicious", "savory", "sweet",
                "food blog", "cookbook", "food show",
                "baking", "pastry", "bread", "cake", "cookie",
                "barbecue", "picnic", "food festival",
                "food culture", "ethnic food", "fusion cuisine"
            ],
            "hobby": [
                "hobby", "pastime", "leisure", "activity",
                "interest", "craft", "collection", "DIY",
                "gardening", "reading", "writing", "photography",
                "painting", "drawing", "sculpting", "knitting",
                "sewing", "crochet", "woodworking", "model building",
                "puzzle solving", "board games", "card games",
                "chess", "sports", "fitness", "yoga", "meditation",
                "hiking", "camping", "video games", "fishing",
                "stargazing", "stamp collecting", "dancing",
                "antiquing", "scrapbooking", "quilting", "pottery",
                "calligraphy", "origami", "homebrewing",
                "wine tasting", "cooking", "baking", "dancing",
                "singing", "playing instrument",
                "learning language", "traveling", "blogging",
                "vlogging", "podcasting", "cosplay", "roleplaying",
                "make", "create", "practice", "collect", "build",
                "explore", "study", "perform", "compete", "bujo",
                "bullet journal", "journal", "journaling", "lettering",
                "paint making", "paint mulling", "filming",
                "content creation"
            ],
            "video games": [
                "video game", "videogame", "console", "nintendo", "sony",
                "microsoft", "xbox", "playstation", "switch", "wii u",
                "wiiU", "game", "play", "gameboy", "game console",
                "gameboy advance", "gamecube", "gaming", "gamer", "ds",
                "3ds", "wii", "gaming PC", "PC", "steam", "epic games",
                "gamepass", "character", "level", "quest", "mission",
                "achievement", "boss", "mini boss", "npc", "farm", "raid",
                "dungeon", "map", "explore", "mmorpg", "rpg", "jrpg",
                "platformer", "roguelike", "sandbox", "stream", "mod",
                "complete", "gameplay", "dlc", "expansion", "server",
                "multiplayer", "unlock", "defeat", "grind", "speedrun",
                "respawn", "save", "single player", "pvp", "pve", "co-op",
                "singleplayer", "discord", "controller", "mouse", "keyboard"
            ],
            "streaming": [
                "streaming", "broadcast", "moderator", "mods", "mod",
                "vip", "chat", "raid", "stream", "host", "clip",
                "subscribe", "sub", "subs", "follow", "streaming setup",
                "schedule", "stream schedule", "live", "viewer",
                "donation", "bits", "emote", "overlay", "overlay",
                "alert", "follower", "lurk", "scenes", "sources",
                "obs", "streamelements", "streamlabs", "twitch",
                "stream setup", "stream title", "stream category",
                "youtube", "mic", "gaming pc", "gaming laptop", "pc",
                "laptop", "streaming item", "streaming accessory"
            ],
            "vtubing": [
                "vtubing item", "debut", "redebut", "redesign", "outfit",
                "agency", "independent", "indie", "stream", "track",
                "animate", "design", "commission", "customize", "update",
                "vshojo", "hololive", "idolcorp", "idolen", "idoles",
                "niji", "anycolor", "nijisanji", "phase connect",
                "prprlive", "model reveal", "outfit reveal",
                "vtubing item", "vtubing accessory", "vtubing setup"
            ],
            "live2d rigging": [
                "Live2D", "Live2D Cubism", "Vtuber", "model", "avatar",
                "png tuber", "rig", "expression", "emotion", "emote",
                "tracking", "face tracking", "3d model", "vroid",
                "vbridger", "mocap", "motion capture", "capture",
                "vtube studio", "rigging stream", "rigging", "tablet"
            ],
            "drawing": [
                "drawing item", "drawing tool", "art", "drawing",
                "painting", "sketching", "sketch", "draw",
                "illustration", "artwork", "canvas", "tablet",
                "digital tablet", "drawing tablet", "wacom", "huion",
                "xp-pen", "pen", "pencil", "sketchbook", "sketch pad",
                "sketch pen", "tablet pen", "tablet screen",
                "monitor tablet", "intuos", "bamboo", "drivers",
                "photoshop", "paint tool sai", "sai", "procreate",
                "gimp", "krita", "illustrator", "artisul", "commission",
                "clip studio", "art stream", "art program", "doodle",
                "composition", "stylus", "mouse", "brush", "paintbrush",
                "paint", "watercolor", "watercolour", "layer",
                "palette", "swatch", "perspective", "anatomy",
                "shading", "highlight", "lineart", "wip",
                "work in progress", "line art", "flats", "reference",
                "compose", "erase", "blend", "color", "colour",
                "render", "design", "edit", "study", "practice",
                "art tutorial", "art program", "art reference",
                "drawing session", "art jam"
            ],
            "coding": [
                "coding", "code", "program", "programming", "develop",
                "engineer", "developer", "programmer", "app",
                "application", "framework", "library", "module", "api",
                "database", "sql", "sequel", "server", "frontend",
                "backend", "fullstack", "algorithm", "prompt",
                "engineering", "class", "function", "method",
                "variable", "constant", "global", "static", "syntax",
                "complier", "ide", "repository", "interpreter",
                "branch", "main", "commit", "debug", "debugging",
                "test", "unit testing", "implement", "run", "push",
                "git", "pull", "merge", "refactor", "optimize",
                "maintain", "update", "deploy", "compile", "visual studio",
                "vscode", "intellij", "pycharm", "github", "gitlab",
                "bitbucket", "jira", "stack overflow", "terminal",
                "command prompt", "shell", "bash", "linux", "windows",
                "powershell", "command line", "environment",
                "virtual environment", "development environment",
                "coding language", "coding session", "programming language"
            ],
            "projects": [
                "project", "task", "goal", "objective", "plan",
                "initiative", "venture", "undertaking", "endeavor",
                "assignment", "mission", "campaign", "program",
                "scheme", "enterprise", "development", "creation",
                "construction", "renovation", "restoration",
                "research", "study", "experiment", "investigation",
                "analysis", "design", "prototype", "model",
                "implementation", "launch", "rollout", "deployment",
                "startup", "business plan", "fundraising",
                "home improvement", "garden makeover", "landscaping",
                "art installation", "music composition", "film production",
                "book writing", "blog series", "podcast series",
                "online course creation", "workshop organization",
                "online course", "web development", "web design",
                "event planning", "travel planning", "fitness challenge",
                "diet plan", "skill acquisition", "language learning",
                "coding project", "app development", "website creation",
                "data analysis", "machine learning model",
                "sustainability initiative", "recycling program",
                "career development", "personal growth",
                "start", "plan", "develop", "implement", "complete",
                "organize", "manage", "lead", "coordinate", "execute",
                "agenda", "planner", "schedule", "timeline", "trello",
                "jira", "slack", "confluence"
            ],
            "social media and content creation": [
                "content creation", "content creator", "influencer",
                "blog", "vlog", "podcast", "YouTube channel",
                "streaming", "video editing", "photo editing",
                "script writing", "storyboarding", "filming",
                "recording", "editing", "publishing", "social media",
                "Facebook", "Instagram", "Twitter", "TikTok", 
                "LinkedIn", "Pinterest", "Reddit", "Tumblr",
                "Discord", "Twitch", "YouTube", "repost", "reblog",
                "post", "share", "like", "comment", "retweet",
                "follow", "unfollow", "subscribe", "story",
                "reel", "tweet", "pin", "DM", "tag", "mention",
                "hashtag", "trending", "viral", "meme", 
                "followers", "subscribers", "views", "engagement",
                "reach", "impressions", "analytics", "insights", 
                "content strategy", "social media strategy",
                "audience growth", "community building",
                "personal branding", "digital marketing",
                "SEO", "social media management", 
                "monetization", "sponsorship", "brand deal",
                "affiliate marketing", "ad revenue", 
                "collaboration", "crossover", "guest appearance",
                "shoutout", "influencer marketing", 
                "live streaming", "Q&A session", "AMA",
                "behind the scenes", "interactive content", 
                "photo", "video", "text post", "article",
                "infographic", "animation", "GIF", "poll",
                "survey", "user-generated content", 
                "create", "produce", "edit", "publish", "promote",
                "grow", "engage", "collaborate", "monetize",
                "network", "interact", "influence", "curate"
            ]
        }
        self.extract_category_mapping = {
            "music": ("extract_music", [
                    "instrument", "music", "song",
                    "band", "artist", "genre", "album",
                    "track", "playlist", "melody", "listen",
                    "play", "sing", "compose", "lyric",
                    "spotify", "streaming", "concert", "radio",
                    "festival", "headphones", "earbuds", "speakers"
            ]),
            "food": ("extract_food_and_cooking", [
                "food", "dish", "meal", "snack", "drink", "beverage",
                "breakfast", "lunch", "dinner", "brunch",
                "menu", "restaurant", "dining", "cuisine",
                "taste", "flavor", "eat", "cook", "bake", "prepare",
                "recipe", "ingredient", "spice", "herb",
                "appetizer", "main course", "dessert",
                "grill", "roast", "fry", "boil", "steam",
                "kitchen", "oven", "stove", "cookware",
                "chef", "culinary", "gastronomy",
                "vegetarian", "vegan", "gluten-free", "organic",
                "homemade", "takeout", "fast food",
                "nutritious", "delicious", "savory", "sweet",
                "food blog", "cookbook", "food show",
                "baking", "pastry", "bread", "cake", "cookie",
                "barbecue", "picnic", "food festival",
                "food culture", "ethnic food", "fusion cuisine"
            ]),
            "hobby": ("extract_hobbies", [
                "hobby", "pastime", "leisure", "activity",
                "interest", "craft", "collection", "DIY",
                "gardening", "reading", "writing", "photography",
                "painting", "drawing", "sculpting", "knitting",
                "sewing", "crochet", "woodworking", "model building",
                "puzzle solving", "board games", "card games",
                "chess", "sports", "fitness", "yoga", "meditation",
                "hiking", "camping", "video games", "fishing",
                "stargazing", "stamp collecting", "dancing",
                "antiquing", "scrapbooking", "quilting", "pottery",
                "calligraphy", "origami", "homebrewing",
                "wine tasting", "cooking", "baking", "dancing",
                "singing", "playing instrument",
                "learning language", "traveling", "blogging",
                "vlogging", "podcasting", "cosplay", "roleplaying",
                "make", "create", "practice", "collect", "build",
                "explore", "study", "perform", "compete", "bujo",
                "bullet journal", "journal", "journaling", "lettering",
                "paint making", "paint mulling", "filming",
                "content creation"
            ]),
            "video games": ("extract_video_games", [
                "video game", "videogame", "console", "nintendo", "sony",
                "microsoft", "xbox", "playstation", "switch", "wii u",
                "wiiU", "game", "play", "gameboy", "game console",
                "gameboy advance", "gamecube", "gaming", "gamer", "ds",
                "3ds", "wii", "gaming PC", "PC", "steam", "epic games",
                "gamepass", "character", "level", "quest", "mission",
                "achievement", "boss", "mini boss", "npc", "farm", "raid",
                "dungeon", "map", "explore", "mmorpg", "rpg", "jrpg",
                "platformer", "roguelike", "sandbox", "stream", "mod",
                "complete", "gameplay", "dlc", "expansion", "server",
                "multiplayer", "unlock", "defeat", "grind", "speedrun",
                "respawn", "save", "single player", "pvp", "pve", "co-op",
                "singleplayer", "discord", "controller", "mouse", "keyboard"
            ]),
            "streaming": ("extract_streaming", [
                "streaming", "broadcast", "moderator", "mods", "mod",
                "vip", "chat", "raid", "stream", "host", "clip",
                "subscribe", "sub", "subs", "follow", "streaming setup",
                "schedule", "stream schedule", "live", "viewer",
                "donation", "bits", "emote", "overlay", "overlay",
                "alert", "follower", "lurk", "scenes", "sources",
                "obs", "streamelements", "streamlabs", "twitch",
                "stream setup", "stream title", "stream category",
                "youtube", "mic", "gaming pc", "gaming laptop", "pc",
                "laptop", "streaming item", "streaming accessory"
            ]),
            "vtubing": ("extract_vtubing", [
                "vtubing item", "debut", "redebut", "redesign", "outfit",
                "agency", "independent", "indie", "stream", "track",
                "animate", "design", "commission", "customize", "update",
                "vshojo", "hololive", "idolcorp", "idolen", "idoles",
                "niji", "anycolor", "nijisanji", "phase connect",
                "prprlive", "model reveal", "outfit reveal",
                "vtubing item", "vtubing accessory", "vtubing setup"
            ]),
            "live2d rigging": ("extract_live2d", [
                "Live2D", "Live2D Cubism", "Vtuber", "model", "avatar",
                "png tuber", "rig", "expression", "emotion", "emote",
                "tracking", "face tracking", "3d model", "vroid",
                "vbridger", "mocap", "motion capture", "capture",
                "vtube studio", "rigging stream", "rigging", "tablet"
            ]),
            "drawing": ("extract_drawing", [
                "drawing item", "drawing tool", "art", "drawing",
                "painting", "sketching", "sketch", "draw",
                "illustration", "artwork", "canvas", "tablet",
                "digital tablet", "drawing tablet", "wacom", "huion",
                "xp-pen", "pen", "pencil", "sketchbook", "sketch pad",
                "sketch pen", "tablet pen", "tablet screen",
                "monitor tablet", "intuos", "bamboo", "drivers",
                "photoshop", "paint tool sai", "sai", "procreate",
                "gimp", "krita", "illustrator", "artisul", "commission",
                "clip studio", "art stream", "art program", "doodle",
                "composition", "stylus", "mouse", "brush", "paintbrush",
                "paint", "watercolor", "watercolour", "layer",
                "palette", "swatch", "perspective", "anatomy",
                "shading", "highlight", "lineart", "wip",
                "work in progress", "line art", "flats", "reference",
                "compose", "erase", "blend", "color", "colour",
                "render", "design", "edit", "study", "practice",
                "art tutorial", "art program", "art reference",
                "drawing session", "art jam"
            ]),
            "coding": ("extract_coding", [
                "coding", "code", "program", "programming", "develop",
                "engineer", "developer", "programmer", "app",
                "application", "framework", "library", "module", "api",
                "database", "sql", "sequel", "server", "frontend",
                "backend", "fullstack", "algorithm", "prompt",
                "engineering", "class", "function", "method",
                "variable", "constant", "global", "static", "syntax",
                "complier", "ide", "repository", "interpreter",
                "branch", "main", "commit", "debug", "debugging",
                "test", "unit testing", "implement", "run", "push",
                "git", "pull", "merge", "refactor", "optimize",
                "maintain", "update", "deploy", "compile", "visual studio",
                "vscode", "intellij", "pycharm", "github", "gitlab",
                "bitbucket", "jira", "stack overflow", "terminal",
                "command prompt", "shell", "bash", "linux", "windows",
                "powershell", "command line", "environment",
                "virtual environment", "development environment",
                "coding language", "coding session", "programming language"
            ]),
            "projects": ("extract_projects", [
                "project", "task", "goal", "objective", "plan",
                "initiative", "venture", "undertaking", "endeavor",
                "assignment", "mission", "campaign", "program",
                "scheme", "enterprise", "development", "creation",
                "construction", "renovation", "restoration",
                "research", "study", "experiment", "investigation",
                "analysis", "design", "prototype", "model",
                "implementation", "launch", "rollout", "deployment",
                "startup", "business plan", "fundraising",
                "home improvement", "garden makeover", "landscaping",
                "art installation", "music composition", "film production",
                "book writing", "blog series", "podcast series",
                "online course creation", "workshop organization",
                "online course", "web development", "web design",
                "event planning", "travel planning", "fitness challenge",
                "diet plan", "skill acquisition", "language learning",
                "coding project", "app development", "website creation",
                "data analysis", "machine learning model",
                "sustainability initiative", "recycling program",
                "career development", "personal growth",
                "start", "plan", "develop", "implement", "complete",
                "organize", "manage", "lead", "coordinate", "execute",
                "agenda", "planner", "schedule", "timeline", "trello",
                "jira", "slack", "confluence"
            ]),
            "social media and content creation": ("extract_social_and_content", [
                    "content creation", "content creator", "influencer",
                    "blog", "vlog", "podcast", "YouTube channel",
                    "streaming", "video editing", "photo editing",
                    "script writing", "storyboarding", "filming",
                    "recording", "editing", "publishing", "social media",
                    "Facebook", "Instagram", "Twitter", "TikTok", 
                    "LinkedIn", "Pinterest", "Reddit", "Tumblr",
                    "Discord", "Twitch", "YouTube", "repost", "reblog",
                    "post", "share", "like", "comment", "retweet",
                    "follow", "unfollow", "subscribe", "story",
                    "reel", "tweet", "pin", "DM", "tag", "mention",
                    "hashtag", "trending", "viral", "meme", 
                    "followers", "subscribers", "views", "engagement",
                    "reach", "impressions", "analytics", "insights", 
                    "content strategy", "social media strategy",
                    "audience growth", "community building",
                    "personal branding", "digital marketing",
                    "SEO", "social media management", 
                    "monetization", "sponsorship", "brand deal",
                    "affiliate marketing", "ad revenue", 
                    "collaboration", "crossover", "guest appearance",
                    "shoutout", "influencer marketing", 
                    "live streaming", "Q&A session", "AMA",
                    "behind the scenes", "interactive content", 
                    "photo", "video", "text post", "article",
                    "infographic", "animation", "GIF", "poll",
                    "survey", "user-generated content", 
                    "create", "produce", "edit", "publish", "promote",
                    "grow", "engage", "collaborate", "monetize",
                    "network", "interact", "influence", "curate"
                ])
        }

    async def get_classification_mapping(self):
        return self.base_category_mapping
    
    async def get_extraction_mapping(self):
        return self.extract_category_mapping
    
    async def get_categories(self):
        return self.categories